format:
  html:
    embed-resources: true
  revealjs:
    theme: [default, custom.scss]
    toc: true
    toc-depth: 1
    slide-number: c/t
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: _images/tamu.png
    css: styles.css
    highlight-style: a11y
    footer: "Darren Homrighausen [https://darrenho.github.io/](https://darrenho.github.io/)"
    preload-iframes: true
