format:
  revealjs:
    theme: [default, custom]
    toc: true
    toc-depth: 1
    slide-number: c/t
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: _images/tamu.png
    css: styles.css
    highlight-style: a11y
    footer: "[https://darrenho.github.io/](https://darrenho.github.io/)"
  html:
    html-math-method: webtex