project:
  output-dir: _slides
format:
  html:
    html-math-method: webtex
  revealjs:
    theme:
      - default
      - dark
      - custom
    toc: true
    slide-number: c/t
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: /images/tamu.png
    css: styles.css
    highlight-style: a11y
    footer: "[https://darrenho.github.io/](https://darrenho.github.io/)"